image: Ubuntu

stack: jdk 11

branches:
  only:
    - master
    - jsonSchema

build: off

install:

  - java -jar ./artifacts/app-mbank.jar &
  - chmod +x gradlew

build_script:
  - ./gradlew test --info